services:
  app:
    container_name: urlshortener
    depends_on:
      - redis
    networks:
      - urlshortener-network
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./config/keys/:/app/config/keys/:ro
      - ~/.aws/:/home/urlshortener/.aws/:ro

  redis:
    image: redis:7
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    networks:
      - urlshortener-network
    ports:
      - "6379:6379"
    volumes:
      - ./compose/redis/redis.conf:/etc/redis/redis.conf:ro
      - ./compose/redis:/redis/data/

networks:
  urlshortener-network:
    driver: bridge
